[WIP] showcases layerの追加
PublicHIKKY/vket-boilerplate-nuxt pull request #12
Opened 2024-12-19 02:56 UTC by shota-ito

### Ticket, Issues
- 無し

### Actions
- baseレイヤーはlibに依存するようなものを入れない構成にとなっているのですが、libに依存するようなコンポーネントなどを実装するためのレイヤーを追加しました。

### Points and Notes
- 

### Evidences
-

2024-12-19 08:00 UTC, shota-ito reviewed
補足情報コメントしました

2024-12-19 08:00 UTC, shota-ito commented on layers/base/tsconfig.json
> -    }
nuxt.config.tsのaliasを追加しているため「.nuxt/tsconfig.json」にこのpathが吐き出されており削除しても動きそうなので消しています。

2024-12-19 08:00 UTC, shota-ito commented on layers/main/tsconfig.json
> +    "../../tsconfig.shared.json"
baseを継承する必要が無いのでbaseを継承するのをやめて、baseと同じtsconfigを継承するようにしました。
baseで定義している型定義類についてはnuxtレイヤーが「.nuxt/tsconfig.json」にマージしてくれるので大丈夫そうです。
また「../base/tsconfig.json」を継承すると自身のレイヤーのpathがunknownになるようでした。

2024-12-19 08:00 UTC, shota-ito commented on layers/main/tsconfig.json
> +    ],
pathsについては
nuxt.config.tsのaliasを追加しているため「.nuxt/tsconfig.json」にこのpathが吐き出されており削除しても動きそうなので消しています。

tpyesを追加した理由はこれが無いとサーバー起動時にvitest周りでたくさんエラーが出るのでbaseに定義している情報と同じにするようにしました。

2024-12-19 08:00 UTC, shota-ito commented on layers/showcases/tsconfig.json
mainレイヤーのtsconfig.jsonと同じにしています。

2024-12-19 08:12 UTC, shota-ito commented on layers/base/app/composables/useToast.ts
> +    type?: 'info' | 'success' | 'error' | 'warning',
ToastTypeには「loading、default」の定義もあるのですが、これがついているとエラーになるので調整しました。

2024-12-19 14:37 UTC, Skmt3P requested changes
ちょっとこれ影響が大きい上に私の方で確認できてないことやろうとしてるので、この変更は飲めないです。

できれば、このPRはshowcasesの追加だけにとどめて、mainとbaseには手を入れないでください。

2024-12-19 14:37 UTC, Skmt3P commented on layers/main/package.json
> +    "vket-boilerplace-nuxt-showcases": "workspace:*"
[must] あー、これはだめかな。これやっちゃうとshowcasesに分けてる意味がなくなっちゃう。これをいれるかどうかはPJ判断になると思ってます。少なくともOSSの時点ではやらないです。

2024-12-19 14:37 UTC, Skmt3P commented on layers/main/tsconfig.json
> +    "../../tsconfig.shared.json"
[must] ちょっとこのファイルの変更は影響がデカすぎるのでやめてください。これやるなら、同期で私と確認しつつにしてもらっていいですか？

2024-12-19 14:37 UTC, Skmt3P commented
あと、CI落ちてるので直して欲しいかな...あとCIファイルの追加も必要になると思います。

2024-12-20 13:15 UTC, aiya000 commented on layers/base/app/composables/useToast.ts
> +    type?: 'info' | 'success' | 'error' | 'warning',
すみません、忙しくてここ以外レビューできそうにないのですが、ここはLGTMです～！！

2025-01-01 07:44 UTC, Skmt3P approved these changes
LGTMerge!

2025-01-01 07:45 UTC, merged